refresh_interval = 1000

[[modules]]
name = "cmd"
instance = "0"
format = 'printf "💡 %s" "$(brightnessctl i | grep -o "([0-9]\\+%)" | tr -d "()")"'
html_escape = true
#format = "echo '$(brightnessctl i | grep -oP '\(\K[0-9]+(?=%\))')%'"

[[modules]]
name = "battery"
instance = "0"
format = "🔋 {state_of_charge:{:5.1}}%"
html_escape = false

[modules.on_click]
Left = [
    "foot",
    "btop",
]

#[[modules]]
#name = "nmcli"
#format = "{bars}"
#html_escape = false
#
#[modules.on_click]
#Left = [
#    "foot",
#    "nmtui",
#]

[[modules]]
name = "pactl"
instance = "0"
format = "🔈 {volume:{:3}}%{muted}"
html_escape = true

[modules.on_click]
WheelUp = [
    "pactl",
    "set-sink-volume",
    "@DEFAULT_SINK@",
    "+1%",
]
Left = ["pavucontrol"]
Right = [
    "pactl",
    "set-sink-mute",
    "@DEFAULT_SINK@",
    "toggle",
]
WheelDown = [
    "pactl",
    "set-sink-volume",
    "@DEFAULT_SINK@",
    "-1%",
]

[[modules]]
name = "nmcli"
instance = "0"
format = "{bars}"
html_escape = true

[modules.on_click]
Left=["foot","nmtui"]

[[modules]]
name = "date"
instance = "0"
format = "⏰ %d %b %R"
html_escape = false
